In [3]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
trains=pd.read_csv("isl_wise_train_detail_03082015_v1.csv")

In [4]:
%matplotlib inline

In [5]:
 import os

In [8]:
trains.shape

(69006, 12)

In [9]:
trains.head()

,Train No.,train Name,islno,station Code,Station Name,Arrival time,Departure time,Distance,Source Station Code,source Station Name,Destination station Code,Destination Station Name
0,'00851',BNC SUVIDHA SPL,1,BBS,BHUBANESWAR,'00:00:00','22:50:00',0,BBS,BHUBANESWAR,BNC,BANGALORE CANT
1,'00851',BNC SUVIDHA SPL,2,BAM,BRAHMAPUR,'01:10:00','01:12:00',166,BBS,BHUBANESWAR,BNC,BANGALORE CANT
2,'00851',BNC SUVIDHA SPL,3,VSKP,VISAKHAPATNAM,'05:10:00','05:30:00',443,BBS,BHUBANESWAR,BNC,BANGALORE CANT
3,'00851',BNC SUVIDHA SPL,4,BZA,VIJAYAWADA JN,'11:10:00','11:20:00',793,BBS,BHUBANESWAR,BNC,BANGALORE CANT
4,'00851',BNC SUVIDHA SPL,5,RU,RENIGUNTA JN,'16:42:00','16:52:00',1169,BBS,BHUBANESWAR,BNC,BANGALORE CANT

In [11]:
trains.ix[15]

Train No.                           '01081'
train Name                  DR BSL T F SPL
islno                                     2
station Code                           TNA
Station Name                THANE
Arrival time                     '22:03:00'
Departure time                   '22:05:00'
Distance                                 25
Source Station Code                    DR
source Station Name         DADAR
Destination station Code               BSL
Destination Station Name    BHUSAVAL JN
Name: 15, dtype: object

In [16]:
trains.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 69006 entries, 0 to 69005
Data columns (total 12 columns):
Train No.                   69006 non-null object
train Name                  69006 non-null object
islno                       69006 non-null int64
station Code                69006 non-null object
Station Name                69006 non-null object
Arrival time                69006 non-null object
Departure time              69006 non-null object
Distance                    69006 non-null int64
Source Station Code         69006 non-null object
source Station Name         69006 non-null object
Destination station Code    69006 non-null object
Destination Station Name    69006 non-null object
dtypes: int64(2), object(10)

In [ ]:
trains.loc[3]

In [ ]:
;

In [21]:
train_no.head()

              Train No.       train Name  islno station Code     Station Name  \
Train No.
'00851'   0     '00851'  BNC SUVIDHA SPL      1         BBS   BHUBANESWAR
          1     '00851'  BNC SUVIDHA SPL      2         BAM   BRAHMAPUR
          2     '00851'  BNC SUVIDHA SPL      3         VSKP  VISAKHAPATNAM
          3     '00851'  BNC SUVIDHA SPL      4         BZA   VIJAYAWADA JN
          4     '00851'  BNC SUVIDHA SPL      5         RU    RENIGUNTA JN
'00852'   7     '00852'  BNC BBS SUVIDHA      1         BNC   BANGALORE CANT
          8     '00852'  BNC BBS SUVIDHA      2         JTJ   JOLARPETTAI
          9     '00852'  BNC BBS SUVIDHA      3         RU    RENIGUNTA JN
          10    '00852'  BNC BBS SUVIDHA      4         BZA   VIJAYAWADA JN
          11    '00852'  BNC BBS SUVIDHA      5         VSKP  VISAKHAPATNAM
'01081'   14    '01081'  DR BSL T F SPL       1         DR    DADAR
          15    '01081'  DR BSL T F SPL       2         TNA   THANE
          16    '01081'  DR BSL T F SPL       3         KYN   KALYAN JN
          17    '01081'  DR BSL T F SPL       4         IGP   IGATPURI
          18    '01081'  DR BSL T F SPL       5         NK    NASIK ROAD
'01082'   22    '01082'  BSL DR T F SPL       1         BSL   BHUSAVAL JN
          23    '01082'  BSL DR T F SPL       2         JL    JALGAON JN
          24    '01082'  BSL DR T F SPL       3         CSN   CHALISGAON JN
          25    '01082'  BSL DR T F SPL       4         NK    NASIK ROAD
          26    '01082'  BSL DR T F SPL       5         IGP   IGATPURI
'01149'   30    '01149'  BSL CSN T F SPL      1         BSL   BHUSAVAL JN
          31    '01149'  BSL CSN T F SPL      2         JL    JALGAON JN
          32    '01149'  BSL CSN T F SPL      3         PC    PACHORA JN
          33    '01149'  BSL CSN T F SPL      4         CSN   CHALISGAON JN
'01150'   34    '01150'  CSN BSL T F SPL      1         CSN   CHALISGAON JN
          35    '01150'  CSN BSL T F SPL      2         PC    PACHORA JN
          36    '01150'  CSN BSL T F SPL      3         JL    JALGAON JN
          37    '01150'  CSN BSL T F SPL      4         BSL   BHUSAVAL JN
'01151'   38    '01151'  CSN DHI T F SPL      1         CSN   CHALISGAON JN
          39    '01151'  CSN DHI T F SPL      2         JMD   JAMDHA
          40    '01151'  CSN DHI T F SPL      3         SHF   SHIRUD
          41    '01151'  CSN DHI T F SPL      4         DHI   DHULE
'01152'   42    '01152'  DHI CSN T F SPL      1         DHI   DHULE
          43    '01152'  DHI CSN T F SPL      2         SHF   SHIRUD
          44    '01152'  DHI CSN T F SPL      3         JMD   JAMDHA
          45    '01152'  DHI CSN T F SPL      4         CSN   CHALISGAON JN
'01153'   46    '01153'  CSN CSTM T F SP      1         CSN   CHALISGAON JN
          47    '01153'  CSN CSTM T F SP      2         NGN   NANDGAON
          48    '01153'  CSN CSTM T F SP      3         MMR   MANMAD JN
          49    '01153'  CSN CSTM T F SP      4         LS    LASALGAON
          50    '01153'  CSN CSTM T F SP      5         NK    NASIK ROAD
'01154'   58    '01154'  CSTM CSN T F SP      1         CSTM  MUMBAI CST
          59    '01154'  CSTM CSN T F SP      2         DR    DADAR
          60    '01154'  CSTM CSN T F SP      3         TNA   THANE
          61    '01154'  CSTM CSN T F SP      4         KYN   KALYAN JN
          62    '01154'  CSTM CSN T F SP      5         KSRA  KASARA
'01156'   70    '01156'  PVR NAVI KMN SP      1         JM    JALAMB JN
          71    '01156'  PVR NAVI KMN SP      1         PVR   PANDHARPUR
          72    '01156'  PVR NAVI KMN SP      2         KMN   KHAMGAON
          73    '01156'  PVR NAVI KMN SP      2         KWV   KURDUVADI
          74    '01156'  PVR NAVI KMN SP      3         JEUR  JEUR
'01401'   95    '01401'  NGP TTKL FARE S      1         SUR   SOLAPUR JN
          96    '01401'  NGP TTKL FARE S      2         MO    MOHOL
          97    '01401'  NGP TTKL FARE S      3         MA    MADHA
          98    '01401'  NGP TTKL FARE S      4         KWV   KURDUVADI
          99    '01401'  NGP TTKL FARE S      5         BTW   BARSI TOWN
'01402'   116   '01402'  NGP SUR T F SPL      1         NGP   NAGPUR
          117   '01402'  NGP SUR T F SPL      2         WR    WARDHA JN
          118   '01402'  NGP SUR T F SPL      3         PLO   PULGAON JN
          119   '01402'  NGP SUR T F SPL      4         DMN   DHAMANGAON
                    ...              ...    ...          ...              ...

              Arrival time Departure time  Distance Source Station Code  \
Train No.
'00851'   0     '00:00:00'     '22:50:00'         0                BBS
          1     '01:10:00'     '01:12:00'       166                BBS
          2     '05:10:00'     '05:30:00'       443                BBS
          3     '11:10:00'     '11:20:00'       793                BBS
          4     '16:42:00'     '16:52:00'      1169                BBS
'00852'   7     '00:00:00'     '01:00:00'         0                BNC
          8     '03:30:00'     '03:32:00'       144                BNC
          9     '06:45:00'     '06:55:00'       342                BNC
          10    '12:20:00'     '12:30:00'       718                BNC
          11    '18:00:00'     '18:20:00'      1069                BNC
'01081'   14    '00:00:00'     '21:45:00'         0                DR
          15    '22:03:00'     '22:05:00'        25                DR
          16    '22:22:00'     '22:45:00'        45                DR
          17    '00:05:00'     '00:10:00'       128                DR
          18    '00:52:00'     '00:55:00'       179                DR
'01082'   22    '00:00:00'     '08:35:00'         0                BSL
          23    '09:00:00'     '09:03:00'        25                BSL
          24    '09:50:00'     '09:52:00'       117                BSL
          25    '11:20:00'     '11:25:00'       258                BSL
          26    '13:25:00'     '13:30:00'       308                BSL
'01149'   30    '00:00:00'     '18:35:00'         0                BSL
          31    '19:10:00'     '19:13:00'        25                BSL
          32    '19:43:00'     '19:45:00'        72                BSL
          33    '21:30:00'     '00:00:00'       117                BSL
'01150'   34    '00:00:00'     '21:50:00'         0                CSN
          35    '22:20:00'     '22:35:00'        45                CSN
          36    '23:07:00'     '23:10:00'        93                CSN
          37    '23:35:00'     '00:00:00'       117                CSN
'01151'   38    '00:00:00'     '21:55:00'         0                CSN
          39    '22:09:00'     '22:10:00'        15                CSN
          40    '22:33:00'     '22:35:00'        36                CSN
          41    '23:05:00'     '00:00:00'        57                CSN
'01152'   42    '00:00:00'     '05:20:00'         0                DHI
          43    '05:45:00'     '05:47:00'        21                DHI
          44    '06:08:00'     '06:30:00'        43                DHI
          45    '06:50:00'     '00:00:00'        57                DHI
'01153'   46    '00:00:00'     '07:45:00'         0                CSN
          47    '08:16:00'     '08:17:00'        43                CSN
          48    '08:50:00'     '09:00:00'        68                CSN
          49    '09:18:00'     '09:19:00'        93                CSN
          50    '09:52:00'     '09:55:00'       141                CSN
'01154'   58    '00:00:00'     '15:35:00'         0                CSTM
          59    '15:49:00'     '15:52:00'         9                CSTM
          60    '16:19:00'     '16:21:00'        34                CSTM
          61    '16:42:00'     '16:45:00'        54                CSTM
          62    '17:55:00'     '18:00:00'       121                CSTM
'01156'   70    '07:40:00'     '08:20:00'       673                PVR
          71    '00:00:00'     '16:00:00'         0                PVR
          72    '08:40:00'     '00:00:00'       685                PVR
          73    '17:10:00'     '17:35:00'        53                PVR
          74    '18:08:00'     '18:10:00'        87                PVR
'01401'   95    '00:00:00'     '15:20:00'         0                SUR
          96    '15:49:00'     '15:50:00'        34                SUR
          97    '16:15:00'     '16:16:00'        63                SUR
          98    '16:30:00'     '16:50:00'        79                SUR
          99    '17:35:00'     '17:37:00'       116                SUR
'01402'   116   '00:00:00'     '15:00:00'         0                NGP
          117   '16:06:00'     '16:09:00'        79                NGP
          118   '16:35:00'     '16:36:00'       109                NGP
          119   '16:53:00'     '16:54:00'       129                NGP
                       ...            ...       ...                 ...

              source Station Name Destination station Code  \
Train No.
'00851'   0       BHUBANESWAR                         BNC
          1       BHUBANESWAR                         BNC
          2       BHUBANESWAR                         BNC
          3       BHUBANESWAR                         BNC
          4       BHUBANESWAR                         BNC
'00852'   7       BANGALORE CANT                      BBS
          8       BANGALORE CANT                      BBS
          9       BANGALORE CANT                      BBS
          10      BANGALORE CANT                      BBS
          11      BANGALORE CANT                      BBS
'01081'   14      DADAR                               BSL
          15      DADAR                               BSL
          16      DADAR                               BSL
          17      DADAR                               BSL
          18      DADAR                               BSL
'01082'   22      BHUSAVAL JN                         DR
          23      BHUSAVAL JN                         DR
          24      BHUSAVAL JN                         DR
          25      BHUSAVAL JN                         DR
          26      BHUSAVAL JN                         DR
'01149'   30      BHUSAVAL JN                         CSN
          31      BHUSAVAL JN                         CSN
          32      BHUSAVAL JN                         CSN
          33      BHUSAVAL JN                         CSN
'01150'   34      CHALISGAON JN                       BSL
          35      CHALISGAON JN                       BSL
          36      CHALISGAON JN                       BSL
          37      CHALISGAON JN                       BSL
'01151'   38      CHALISGAON JN                       DHI
          39      CHALISGAON JN                       DHI
          40      CHALISGAON JN                       DHI
          41      CHALISGAON JN                       DHI
'01152'   42      DHULE                               CSN
          43      DHULE                               CSN
          44      DHULE                               CSN
          45      DHULE                               CSN
'01153'   46      CHALISGAON JN                       CSTM
          47      CHALISGAON JN                       CSTM
          48      CHALISGAON JN                       CSTM
          49      CHALISGAON JN                       CSTM
          50      CHALISGAON JN                       CSTM
'01154'   58      MUMBAI CST                          CSN
          59      MUMBAI CST                          CSN
          60      MUMBAI CST                          CSN
          61      MUMBAI CST                          CSN
          62      MUMBAI CST                          CSN
'01156'   70      PANDHARPUR                          NAVI
          71      PANDHARPUR                          NAVI
          72      PANDHARPUR                          NAVI
          73      PANDHARPUR                          NAVI
          74      PANDHARPUR                          NAVI
'01401'   95      SOLAPUR JN                          NGP
          96      SOLAPUR JN                          NGP
          97      SOLAPUR JN                          NGP
          98      SOLAPUR JN                          NGP
          99      SOLAPUR JN                          NGP
'01402'   116     NAGPUR                              SUR
          117     NAGPUR                              SUR
          118     NAGPUR                              SUR
          119     NAGPUR                              SUR
                              ...                      ...

              Destination Station Name
Train No.
'00851'   0            BANGALORE CANT
          1            BANGALORE CANT
          2            BANGALORE CANT
          3            BANGALORE CANT
          4            BANGALORE CANT
'00852'   7            BHUBANESWAR
          8            BHUBANESWAR
          9            BHUBANESWAR
          10           BHUBANESWAR
          11           BHUBANESWAR
'01081'   14           BHUSAVAL JN
          15           BHUSAVAL JN
          16           BHUSAVAL JN
          17           BHUSAVAL JN
          18           BHUSAVAL JN
'01082'   22           DADAR
          23           DADAR
          24           DADAR
          25           DADAR
          26           DADAR
'01149'   30           CHALISGAON JN
          31           CHALISGAON JN
          32           CHALISGAON JN
          33           CHALISGAON JN
'01150'   34           BHUSAVAL JN
          35           BHUSAVAL JN
          36           BHUSAVAL JN
          37           BHUSAVAL JN
'01151'   38           DHULE
          39           DHULE
          40           DHULE
          41           DHULE
'01152'   42           CHALISGAON JN
          43           CHALISGAON JN
          44           CHALISGAON JN
          45           CHALISGAON JN
'01153'   46           MUMBAI CST
          47           MUMBAI CST
          48           MUMBAI CST
          49           MUMBAI CST
          50           MUMBAI CST
'01154'   58           CHALISGAON JN
          59           CHALISGAON JN
          60           CHALISGAON JN
          61           CHALISGAON JN
          62           CHALISGAON JN
'01156'   70           NEW AMRAVATI
          71           NEW AMRAVATI
          72           NEW AMRAVATI
          73           NEW AMRAVATI
          74           NEW AMRAVATI
'01401'   95           NAGPUR
          96           NAGPUR
          97           NAGPUR
          98           NAGPUR
          99           NAGPUR
'01402'   116          SOLAPUR JN
          117          SOLAPUR JN
          118          SOLAPUR JN
          119          SOLAPUR JN
                                   ...

[13929 rows x 12 columns]

In [1]:
print "hello"

hello

In [2]:
trains=pd.read_csv("isl_wise_train_detail_03082015_v1.csv")

NameError: name 'pd' is not defined

In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import os

trains=pd.read_csv("isl_wise_train_detail_03082015_v1.csv")
train_no =trains.groupby('Train No.')

In [10]:
print train_no

<pandas.core.groupby.SeriesGroupBy object at 0x7f54a8fea990>

In [ ]:
for i in train_no:
    print train_no

In [12]:
type(train_no.size())

pandas.core.series.Series

In [ ]:
train_no.